### ISSUE TITLE
Cannot unmarshal CloudEvent from pubsub push

### ISSUE THREAD

**Issue by majelbstoat** [GoogleCloudPlatform/functions-framework-go#26] opened 2020-05-24 19:02 UTC
Sending a simple cloudevent message results in the following error:

```
Error: specversion: unknown : ""
, while converting event data: {"subscription":"projects\/my-project\/subscriptions\/my-subscription","message":{"data":"eyJ1c2VySWQiOiJBQUVCRlRpdXE0UFNEUEJ5UEEifQ==","messageId":"1","attributes":{"ce-source":"my-app","ce-specversion":"1.0","ce-type":"test.event.signIn","ce-id":"MFkWEgrOHKs44AEADQ","ce-time":"2020-05-24T18:38:18.7759848Z","Content-Type":"application\/json"}}}
```

Formatted event data for clarity:
```json
{
  "subscription": "projects\/my-project\/subscriptions\/my-subscription",
  "message": {
    "data": "eyJ1c2VySWQiOiJBQUVCRlRpdXE0UFNEUEJ5UEEifQ==",
    "messageId": "1",
    "attributes": {
      "ce-source": "my-app",
      "ce-specversion": "1.0",
      "ce-type": "test.event.signIn",
      "ce-id": "MFkWEgrOHKs44AEADQ",
      "ce-time": "2020-05-24T18:38:18.7759848Z",
      "Content-Type": "application\/json"
    }
  }
}
```

**Comment by majelbstoat** [comment] 2020-05-24 19:08
My function is:

```go
package function

import (
	"context"
	"fmt"

	cloudevents "github.com/cloudevents/sdk-go/v2"
)

func CloudEventsFunction(ctx context.Context, e cloudevents.Event) error {
	fmt.Println("RECEIVED")
	return nil
}
```

**Comment by majelbstoat** [comment] 2020-05-24 20:19
Doing more digging, it appears that [isStructuredCloudEvent](https://github.com/GoogleCloudPlatform/functions-framework-go/blob/c3c5ce18242765c9edc41164b7cbfb7817c3727f/funcframework/framework.go#L119) expects cloud event data as headers, but they are instead present in the message attributes.

As a result, the framework attempts to parse the message as a legacyEvent. But, the fields in attributes are `ce-` prefixed, which I'm guessing is why they can't be parsed. (If it's parsed as structured, the ce- prefix is trimmed.)

The headers for the invocation are:

```
 <<<<< map[Accept:[text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2] Connection:[keep-alive] Content-Length:[360] Content-Type:[application/json] User-Agent:[Java/1.8.0_242]] >>>>>
```

I also tried sending a message with specversion 0.3, to see if it was serialised differently, but the same issue happens.

**Comment by majelbstoat** [comment] 2020-05-24 22:05
Well I guess here's the problem. Functions framework uses the v1 of the cloud events SDK, which is no longer documented, nor easily available.

```
cloudevents "github.com/cloudevents/sdk-go"
```

**Comment by tbpg** [comment] 2020-05-29 17:51
Thank you for the report. #27 from @grant might be a duplicate of this.

**Comment by grant** [comment] 2020-06-03 21:18
Hi @majelbstoat, a Pub/Sub push event does not deliver the event in CloudEvent format. It's not a CloudEvent, it's a custom JSON event.

As a result, you're seeing the unmarshal issue

Can you get this sample in the official docs to work?
https://cloud.google.com/functions/docs/calling/pubsub#sample_code

We're currently adding CloudEvent support to this repo.

**Comment by majelbstoat** [comment] 2020-06-03 22:11
I ended up using the cloudevents SDK directly and [creating a custom format to decode it](https://github.com/cloudevents/sdk-go/issues/306#issuecomment-634926847), not entirely unlike the docs. 

> We're currently adding CloudEvent support to this repo.

Great!

**Comment by grant** [comment] 2020-06-08 22:04
We have a PR out for CloudEvent support which will land shortly (https://github.com/GoogleCloudPlatform/functions-framework-go/pull/29)

We'll keep tracking CE support with #27 until it lands, so I'll go ahead and close this issue. We can continue the discussion there if that works. :)

**Closed by grant** 2020-06-08 22:04 UTC
